default_platform(:ios)

platform :ios do
  desc "Push to TestFlight"
  lane :beta do
    
    keychain_path = ENV["KEYCHAIN_PATH"]
    keychain_password = ENV["KEYCHAIN_PASSWORD"]
    
    # 1. API Key 설정
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: true,  
      duration: 1200,
      in_house: false
    )

    sync_code_signing(
      type: "appstore", 
      readonly: true, 
      app_identifier: "com.page.rim",
      keychain_name: keychain_path,        
      keychain_password: keychain_password 
    )

    # 3. 빌드 번호 관리
    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        app_identifier: "com.page.rim"
      ) + 1,
      xcodeproj: "App/Rim.xcodeproj"
    )
    
    # 4. 앱 빌드
    build_app(
      scheme: "Rim",
      workspace: "Rim.xcworkspace",
      configuration: "Release",
      clean: false,
      export_method: "app-store",
      codesigning_identity: "Apple Distribution: Wooyoung No (MAU8HFALP8)",
      export_options: {
        provisioningProfiles: { 
          "com.page.rim" => "match AppStore com.page.rim"
        },
        compileBitcode: false, 
        uploadBitcode: false
      }
    )
    
    # 5. 업로드
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      distribute_external: false,
      app_identifier: "com.page.rim"
    )
  end

  desc "Local Build Test (No Upload)"
  lane :local_test do
    # 1. 인증서 가져오기 (읽기 전용이라 안전함)
    match(type: "appstore", readonly: true, app_identifier: "com.page.rim")
    
    # 2. 앱 빌드 (여기가 터지는지 확인하는 게 목적!)
    build_app(
      scheme: "Rim",
      workspace: "Rim.xcworkspace",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.page.rim" => "match AppStore com.page.rim"
        },
        compileBitcode: false,
        uploadBitcode: false
      }
    )
    
    # 3. 업로드 단계(upload_to_testflight)는 일부러 뺐습니다!
  end
end